# App Name
spring.application.name=spring_security_oauth2_practicle1

# Server Port (HTTPS)
server.port=7878

# 🔐 SSL Configuration
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=123456
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=myapp

# 🔐 OAuth2 Google Configuration
spring.security.oauth2.client.registration.google.client-id=your-client-id
spring.security.oauth2.client.registration.google.client-secret=your-client-secret
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.client-name=Google

# Disable DB auto config
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Logging
logging.level.com.Spring_Security_JWT.*=debug
logging.file.name=./STSLOGS/JWTSPRING/DEMO/practical.log
logging.logback.rollingpolicy.max-file-size=20MB